import BottomBar from '@/components/BottomBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import { MyContextProvider } from '@/components/MyContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
        <MyContextProvider>
          <body className={inter.className}>
            <div className="w-full flex h-full bg-blue-100">
              <div className="w-1/5 h-full bg-white" >
                <BottomBar />
              </div>
              <div className='w-4/5 h-full bg-blue-100'>
                {children}
              </div>
            </div>
          </body>
        </MyContextProvider>
    </html>
  )
}